class ConstructorInfo:
  def __init__(self, name, constructedType, originalName=None):
    self.name = name
    self.constructedType = constructedType
    if (originalName is None):
      self.originalName = name
    else:
      self.originalName = originalName

class FieldInfo:
  def __init__(self, name, projectedType):
    self.name = name
    self.projectedType = projectedType

class DefinitionInfo:
  def __init__(self, name, definingLemma=None, inline=False, margin=60, description=None):
    self.name = name
    self.definingLemma = definingLemma
    self.inline = inline
    self.margin = margin - 10
    self.description = description

class LemmaInfo:
  def __init__(self, name, margin=60, description=None):
    self.name = name
    self.margin = margin - 10
    self.description = description

constructors = \
  [ConstructorInfo("None", "option"),
   ConstructorInfo("Some", "option"),
   ConstructorInfo("Load", "AccessType", originalName="LOAD"),
   ConstructorInfo("Store", "AccessType", originalName="STORE"),
   ConstructorInfo("RawDataType", "DataType", originalName="Raw"),
   ConstructorInfo("CapDataType", "DataType", originalName="Cap"),
   ConstructorInfo("RegPCC", "CapRegister"),
   ConstructorInfo("RegBranchDelayPCC", "CapRegister"),
   ConstructorInfo("RegBranchToPCC", "CapRegister"),
   ConstructorInfo("RegNormal", "CapRegister"),
   ConstructorInfo("RegSpecial", "CapRegister"),
   ConstructorInfo("LoadDataAction", "DomainAction"),
   ConstructorInfo("StoreDataAction", "DomainAction"),
   ConstructorInfo("RestrictCapAction", "DomainAction"),
   ConstructorInfo("LoadCapAction", "DomainAction"),
   ConstructorInfo("StoreCapAction", "DomainAction"),
   ConstructorInfo("SealCapAction", "DomainAction"),
   ConstructorInfo("UnsealCapAction", "DomainAction"),
   ConstructorInfo("RaiseException", "DomainSwitch"),
   ConstructorInfo("InvokeCapability", "DomainSwitch"),
   ConstructorInfo("KeepDomain", "InstructionIntention"),
   ConstructorInfo("SwitchDomain", "InstructionIntention")]

fields = \
  [FieldInfo("Tag", "Capability"),
   FieldInfo("Base", "Capability"),
   FieldInfo("Length", "Capability"),
   FieldInfo("Offset", "Capability"),
   FieldInfo("IsSealed", "Capability"),
   FieldInfo("Perms", "Capability"),
   FieldInfo("UPerms", "Capability"),
   FieldInfo("ObjectType", "Capability"),
   FieldInfo("Reserved", "Capability"),
   FieldInfo("Mem", "state"),
   FieldInfo("Gpr", "state"),
   FieldInfo("LLbit", "state"),
   FieldInfo("KernelMode", "state"),
   FieldInfo("AccessToCU0", "state"),
   FieldInfo("BigEndian", "state"),
   FieldInfo("ReverseEndian", "state"),
   FieldInfo("EXL", "state"),
   FieldInfo("PC", "state"),
   FieldInfo("PCC", "state"),
   FieldInfo("BranchDelay", "state"),
   FieldInfo("BranchTo", "state"),
   FieldInfo("BranchDelayPCC", "state"),
   FieldInfo("BranchToPCC", "state"),
   FieldInfo("GeneralCapReg", "state"),
   FieldInfo("SpecialCapReg", "state"),
   FieldInfo("IsUnpredictable", "state"),
   FieldInfo("ExceptionSignalled", "state"),
   FieldInfo("SystemRegisterAccess", "GeneralisedPerm"),
   FieldInfo("ExecutableAddresses", "GeneralisedPerm"),
   FieldInfo("LoadableAddresses", "GeneralisedPerm"),
   FieldInfo("CapLoadableAddresses", "GeneralisedPerm"),
   FieldInfo("StorableAddresses", "GeneralisedPerm"),
   FieldInfo("CapStorableAddresses", "GeneralisedPerm"),
   FieldInfo("LocalCapStorableAddresses", "GeneralisedPerm"),
   FieldInfo("SealableTypes", "GeneralisedPerm"),
   FieldInfo("UnsealableTypes", "GeneralisedPerm")]

# To make sure that Isabelle does not think the line continues while it actually
# breaks, we give it an explicit margin. A lower number means Isabelle thinks there is 
# less space for the theorem. Current value found by trial and error.

definitions = \
  [DefinitionInfo("Bit"),
   DefinitionInfo("WordToInt"),
   DefinitionInfo("WordToNat"),
   DefinitionInfo("UCast"),
   DefinitionInfo("SCast"),
   DefinitionInfo("WordCat"),
   DefinitionInfo("Slice"),
   DefinitionInfo("Mask"),
   DefinitionInfo("ExtractByte"),
   DefinitionInfo("Size"),
   DefinitionInfo("MemSegment", "MemSegment_alt"),
   DefinitionInfo("CapBounds", "CapBounds_alt"),
   DefinitionInfo("BitsToCap"),
   DefinitionInfo("CapToBits"),
   DefinitionInfo("PermitAccessSystemRegisters", "PermitAccessSystemRegisters_alt", inline=True),
   DefinitionInfo("IsInvokable", "IsInvokable_alt", inline=True),
   DefinitionInfo("PermitExecute", "PermitExecute_alt", inline=True),
   DefinitionInfo("PermitLoad", "PermitLoad_alt", inline=True),
   DefinitionInfo("PermitLoadCapability", "PermitLoadCapability_alt", inline=True),
   DefinitionInfo("PermitSeal", "PermitSeal_alt", inline=True),
   DefinitionInfo("PermitUnseal", "PermitUnseal_alt", inline=True),
   DefinitionInfo("PermitStore", "PermitStore_alt", inline=True),
   DefinitionInfo("PermitStoreCapability", "PermitStoreCapability_alt", inline=True),
   DefinitionInfo("PermitStoreLocalCapability", "PermitStoreLocalCapability_alt", inline=True),
   DefinitionInfo("IsGlobal", "IsGlobal_alt", inline=True),
   DefinitionInfo("TagOfDataType", "TagOfDataType_def"),
   DefinitionInfo("MemData", "MemData_alt"),
   DefinitionInfo("MemCap", "MemCap_alt"),
   DefinitionInfo("MemTag", "MemTag_alt"),
   DefinitionInfo("GPR", "GPR_alt"),
   DefinitionInfo("KCC", "KCC_alt", inline=True),
   DefinitionInfo("EPCC", "EPCC_alt", inline=True),
   DefinitionInfo("IDC", "IDC_alt", inline=True),
   DefinitionInfo("DDC", "DDC_alt", inline=True),
   DefinitionInfo("CapReg"),
   DefinitionInfo("Cap"),
   DefinitionInfo("GetCapAddress", "GetCapAddress_alt"),
   DefinitionInfo("ExtendCapAddress", "ExtendCapAddress_alt"),
   DefinitionInfo("TranslateAddr"),
   DefinitionInfo("TranslateBounds", "TranslateBounds_alt"),
   DefinitionInfo("TranslateCapAddresses", "TranslateCapAddresses_alt"),
   DefinitionInfo("ExceptionPCs"),
   DefinitionInfo("EmptyGhostState", "EmptyGhostState_alt"),
   DefinitionInfo("StateIsValid", "StateIsValid_alt"),
   DefinitionInfo("CapDerivationTargets"),
   DefinitionInfo("NextInstruction"),
   DefinitionInfo("UnpredictableNext", "UnpredictableNext_alt"),
   DefinitionInfo("LoadDataProp", "LoadDataProp_alt", margin=75),
   DefinitionInfo("StoreDataProp", "StoreDataProp_alt", margin=70),
   DefinitionInfo("ExecuteProp", "ExecuteProp_alt"),
   DefinitionInfo("LoadCapProp", "LoadCapProp_alt"),
   DefinitionInfo("StoreCapProp", "StoreCapProp_alt", margin=65),
   DefinitionInfo("StoreLocalCapProp", "StoreLocalCapProp_alt"),
   DefinitionInfo("RestrictCapProp", "RestrictCapProp_alt"),
   DefinitionInfo("SealCapProp", "SealCapProp_alt"),
   DefinitionInfo("UnsealCapProp", "UnsealCapProp_alt", margin=60),
   DefinitionInfo("SystemRegisterProp", "SystemRegisterProp_alt"),
   DefinitionInfo("InvokeCapProp", "InvokeCapProp_alt", margin=90),
   DefinitionInfo("ExceptionProp", "ExceptionProp_alt"),
   DefinitionInfo("MemoryInvariant", "MemoryInvariant_alt"),
   DefinitionInfo("CapabilityInvariant", "CapabilityInvariant_alt"),
   DefinitionInfo("ValidStateProp", "ValidStateProp_alt"),
   DefinitionInfo("CU0AccessProp", "CU0AccessProp_alt"),
   DefinitionInfo("CheriAbstraction", "CheriAbstraction_alt"),
   DefinitionInfo("CAndPermActions", "CAndPermActions_alt"),
   DefinitionInfo("CBuildCapActions", "CBuildCapActions_alt"),
   DefinitionInfo("CClearHiActions", "CClearHiActions_alt"),
   DefinitionInfo("CClearLoActions", "CClearLoActions_alt"),
   DefinitionInfo("CClearTagActions", "CClearTagActions_alt"),
   DefinitionInfo("CCopyTypeActions", "CCopyTypeActions_alt"),
   DefinitionInfo("CFromPtrActions", "CFromPtrActions_alt"),
   DefinitionInfo("CGetPCCActions", "CGetPCCActions_alt"),
   DefinitionInfo("CGetPCCSetOffsetActions", "CGetPCCSetOffsetActions_alt"),
   DefinitionInfo("CIncOffsetActions", "CIncOffsetActions_alt"),
   DefinitionInfo("CIncOffsetImmediateActions", "CIncOffsetImmediateActions_alt"),
   DefinitionInfo("CJALRActions", "CJALRActions_alt", margin=55),
   DefinitionInfo("CJRActions", "CJRActions_alt"),
   DefinitionInfo("CLCVirtualAddress", "CLCVirtualAddress_alt"),
   DefinitionInfo("CLCPhysicalAddress", "CLCPhysicalAddress_alt"),
   DefinitionInfo("CLCActions", "CLCActions_alt", margin=55),
   DefinitionInfo("CLLCVirtualAddress", "CLLCVirtualAddress_alt"),
   DefinitionInfo("CLLCPhysicalAddress", "CLLCPhysicalAddress_alt"),
   DefinitionInfo("CLLCActions", "CLLCActions_alt", margin=55),
   DefinitionInfo("CMOVNActions", "CMOVNActions_alt"),
   DefinitionInfo("CMOVZActions", "CMOVZActions_alt"),
   DefinitionInfo("CReadHwrActions", "CReadHwrActions_alt"),
   DefinitionInfo("CMoveActions", "CMoveActions_alt"),
   DefinitionInfo("CSCVirtualAddress", "CSCVirtualAddress_alt"),
   DefinitionInfo("CSCPhysicalAddress", "CSCPhysicalAddress_alt"),
   DefinitionInfo("CSCActions", "CSCActions_alt"),
   DefinitionInfo("CSCCVirtualAddress", "CSCCVirtualAddress_alt"),
   DefinitionInfo("CSCCPhysicalAddress", "CSCCPhysicalAddress_alt"),
   DefinitionInfo("CSCCActions", "CSCCActions_alt"),
   DefinitionInfo("CSealActions", "CSealActions_alt"),
   DefinitionInfo("CSetBoundsActions", "CSetBoundsActions_alt", margin=65),
   DefinitionInfo("CSetBoundsExactActions", "CSetBoundsExactActions_alt"),
   DefinitionInfo("CSetBoundsImmediateActions", "CSetBoundsImmediateActions_alt"),
   DefinitionInfo("CSetOffsetActions", "CSetOffsetActions_alt"),
   DefinitionInfo("CUnsealActions", "CUnsealActions_alt"),
   DefinitionInfo("CWriteHwrActions", "CWriteHwrActions_alt"),
   DefinitionInfo("ERETActions", "ERETActions_alt", margin=60),
   DefinitionInfo("LegacyLoadVirtualAddress", "LegacyLoadVirtualAddress_alt"),
   DefinitionInfo("LegacyLoadPhysicalAddress", "LegacyLoadPhysicalAddress_alt"),
   DefinitionInfo("LegacyLoadActions", "LegacyLoadActions_alt"),
   DefinitionInfo("LBActions", "LBActions_alt"),
   DefinitionInfo("LBUActions", "LBUActions_alt"),
   DefinitionInfo("LHActions", "LHActions_alt"),
   DefinitionInfo("LHUActions", "LHUActions_alt"),
   DefinitionInfo("LWActions", "LWActions_alt"),
   DefinitionInfo("LWUActions", "LWUActions_alt"),
   DefinitionInfo("LLActions", "LLActions_alt"),
   DefinitionInfo("LDActions", "LDActions_alt"),
   DefinitionInfo("LLDActions", "LLDActions_alt"),
   DefinitionInfo("LWLActions", "LWLActions_alt"),
   DefinitionInfo("LWRActions", "LWRActions_alt"),
   DefinitionInfo("LDLActions", "LDLActions_alt"),
   DefinitionInfo("LDRActions", "LDRActions_alt"),
   DefinitionInfo("CLoadVirtualAddress", "CLoadVirtualAddress_alt"),
   DefinitionInfo("CLoadPhysicalAddress", "CLoadPhysicalAddress_alt"),
   DefinitionInfo("CLoadActions", "CLoadActions_alt"),
   DefinitionInfo("CLLxVirtualAddress", "CLLxVirtualAddress_alt"),
   DefinitionInfo("CLLxPhysicalAddress", "CLLxPhysicalAddress_alt"),
   DefinitionInfo("CLLxActions", "CLLxActions_alt"),
   DefinitionInfo("LegacyStoreVirtualAddress", "LegacyStoreVirtualAddress_alt"),
   DefinitionInfo("LegacyStorePhysicalAddress", "LegacyStorePhysicalAddress_alt"),
   DefinitionInfo("LegacyStoreActions", "LegacyStoreActions_alt"),
   DefinitionInfo("SBActions", "SBActions_alt"),
   DefinitionInfo("SHActions", "SHActions_alt"),
   DefinitionInfo("SWActions", "SWActions_alt"),
   DefinitionInfo("SDActions", "SDActions_alt"),
   DefinitionInfo("SCActions", "SCActions_alt"),
   DefinitionInfo("SCDActions", "SCDActions_alt"),
   DefinitionInfo("SWLActions", "SWLActions_alt"),
   DefinitionInfo("SWRActions", "SWRActions_alt"),
   DefinitionInfo("SDLActions", "SDLActions_alt"),
   DefinitionInfo("SDRActions", "SDRActions_alt"),
   DefinitionInfo("CStoreVirtualAddress", "CStoreVirtualAddress_alt"),
   DefinitionInfo("CStorePhysicalAddress", "CStorePhysicalAddress_alt"),
   DefinitionInfo("CStoreActions", "CStoreActions_alt"),
   DefinitionInfo("CSCxVirtualAddress", "CSCxVirtualAddress_alt"),
   DefinitionInfo("CSCxPhysicalAddress", "CSCxPhysicalAddress_alt"),
   DefinitionInfo("CSCxActions", "CSCxActions_alt"),
   DefinitionInfo("RunActions"),
   DefinitionInfo("TakeBranchActions", "TakeBranchActions_alt"),
   DefinitionInfo("DomainActions", "DomainActions_alt"),
   DefinitionInfo("Next"),
   DefinitionInfo("NextWithGhostState"),
   DefinitionInfo("SemanticsCheriMips", "SemanticsCheriMips_alt", margin=70),
   DefinitionInfo("BotGeneralisedPerm"),
   DefinitionInfo("TopGeneralisedPerm"),
   DefinitionInfo("RegisterIsAlwaysAccessible", "RegisterIsAlwaysAccessible_alt"),
   DefinitionInfo("ReadableLocations", "ReadableLocations_alt"),
   DefinitionInfo("StorablePhysAddresses", "StorablePhysAddresses_alt"),
   DefinitionInfo("StorablePhysCapAddresses", "StorablePhysCapAddresses_alt"),
   DefinitionInfo("GPermOfCap", "GPermOfCap_alt", margin=55),
   DefinitionInfo("GPermOfCaps", "GPermOfCaps_alt"),
   DefinitionInfo("ReachableCaps"),
   DefinitionInfo("TransUsableCaps", "TransUsableCaps_alt"),
   DefinitionInfo("ReachablePermissions", "ReachablePermissions_alt"),
   DefinitionInfo("FutureStates"),
   DefinitionInfo("KeepsDomain"),
   DefinitionInfo("SwitchesDomain"),
   DefinitionInfo("IntraDomainTrace"),
   DefinitionInfo("InterDomainTrace"),
   DefinitionInfo("MonotonicityReachableCaps", "MonotonicityReachableCaps_alt"),
   DefinitionInfo("SameDomainSystemRegInvariant", "SameDomainSystemRegInvariant_alt"),
   DefinitionInfo("DomainCrossSystemRegInvariant", "DomainCrossSystemRegInvariant_alt"),
   DefinitionInfo("SameDomainMemCapInvariant", "SameDomainMemCapInvariant_alt"),
   DefinitionInfo("DomainCrossMemCapInvariant", "DomainCrossMemCapInvariant_alt"),
   DefinitionInfo("SameDomainMemoryInvariant", "SameDomainMemoryInvariant_alt"),
   DefinitionInfo("DomainCrossMemoryInvariant", "DomainCrossMemoryInvariant_alt"),
   DefinitionInfo("PermIsClosed", "PermIsClosed_alt"),
   DefinitionInfo("CapabilityAligned", "CapabilityAligned_alt"),
   DefinitionInfo("AccessibleCaps", "AccessibleCaps_alt"),
   DefinitionInfo("UsableCaps", "UsableCaps_alt"),
   DefinitionInfo("InvokableCaps", "InvokableCaps_alt"),
   DefinitionInfo("InvokableAddresses", "InvokableAddresses_alt"),
   DefinitionInfo("NoSystemRegisterAccess", "NoSystemRegisterAccess_alt"),
   DefinitionInfo("ContainedCapBounds", "ContainedCapBounds_alt"),
   DefinitionInfo("ContainedObjectTypes", "ContainedObjectTypes_alt"),
   DefinitionInfo("InvokableCapsNotUsable", "InvokableCapsNotUsable_alt"),
   DefinitionInfo("IsolatedState", "IsolatedState_alt", margin=70),
   DefinitionInfo("IsolationGuarantees", "IsolationGuarantees_alt", margin=80),
   DefinitionInfo("CompartmentIsolation", "CompartmentIsolation_alt", margin=70)]

lemmas = \
  [LemmaInfo("CapabilityOrder"),
   LemmaInfo("LoadDataInstantiation"),
   LemmaInfo("StoreDataInstantiation"),
   LemmaInfo("ExecuteInstantiation"),
   LemmaInfo("LoadCapInstantiation"),
   LemmaInfo("StoreCapInstantiation"),
   LemmaInfo("StoreLocalCapInstantiation"),
   LemmaInfo("RestrictCapInstantiation"),
   LemmaInfo("SealCapInstantiation"),
   LemmaInfo("UnsealCapInstantiation"),
   LemmaInfo("SystemRegisterInstantiation"),
   LemmaInfo("InvokeCapInstantiation"),
   LemmaInfo("ExceptionInstantiation"),
   LemmaInfo("MemoryInvariantInstantiation"),
   LemmaInfo("CapabilityInvariantInstantiation"),
   LemmaInfo("ValidStateInstantiation"),
   LemmaInfo("AddressTranslationInstantiation"),
   LemmaInfo("CheriInstantiation"),
   LemmaInfo("GPermOfCap_SystemRegisterAccess"),
   LemmaInfo("GPermOfCap_ExecutableAddresses"),
   LemmaInfo("GPermOfCap_LoadableAddresses"),
   LemmaInfo("GPermOfCap_CapLoadableAddresses"),
   LemmaInfo("GPermOfCap_StorableAddresses"),
   LemmaInfo("GPermOfCap_CapStorableAddresses"),
   LemmaInfo("GPermOfCap_LocalCapStorableAddresses"),
   LemmaInfo("GPermOfCap_SealableTypes"),
   LemmaInfo("GPermOfCap_UnsealableTypes"),
   LemmaInfo("GPermOfCap_le"),
   LemmaInfo("ReachableCaps_Reg"),
   LemmaInfo("ReachableCaps_Memory", margin=50),
   LemmaInfo("ReachableCaps_Restrict"),
   LemmaInfo("ReachableCaps_Seal"),
   LemmaInfo("ReachableCaps_Unseal"),
   LemmaInfo("IntraDomainTrace_Nil"),
   LemmaInfo("IntraDomainTrace_Cons"),
   LemmaInfo("FutureStates_Nil"),
   LemmaInfo("FutureStates_Cons"),
   LemmaInfo("AbstractionImpliesMonotonicityReachableCaps"),
   LemmaInfo("AbstractionImpliesSameDomainSystemRegInvariant"),
   LemmaInfo("AbstractionImpliesDomainCrossSystemRegInvariant"),
   LemmaInfo("AbstractionImpliesSameDomainMemCapInvariant"),
   LemmaInfo("AbstractionImpliesDomainCrossMemCapInvariant"),
   LemmaInfo("AbstractionImpliesSameDomainMemoryInvariant"),
   LemmaInfo("AbstractionImpliesDomainCrossMemoryInvariant"),
   LemmaInfo("AbstractionImpliesCompartmentIsolation")]
